config/routes.rb
Callbreak::Application.routes.draw do
  get "users/new"

  root :to => "callbreak#index"

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy] 

  get "callbreak/index"

  get "callbreak/reset"

end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :image, :number, :suit
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, :presence => true, :length => {:maximum => 50, :minimum => 2}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => true, :format => {:with => VALID_EMAIL_REGEX}, :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true, :length => {:minimum => 6, :maximum => 20}
  validates :password_confirmation, :presence => true

  private

  	def create_remember_token
  		if self.new_record?
        	self.remember_token = SecureRandom.base64
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/callbreak_controller.rb
class CallbreakController < ApplicationController
  def index
  	@cards = Card.order("RANDOM()").all
  	@players_cards = @cards.in_groups(4)
  	@player1 = @players_cards.first
  	@player2 = @players_cards.second
  	@player3 = @players_cards.third
  	@player4 = @players_cards.last
  end

  def reset
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		render 'new'
  	end

  	def create
  		user = User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
		# Sign the user in and redirect to the user's show page.
			sign_in user
      		redirect_back_or user
		else
		# Create an error message and re-render the signin form.
			flash[:error] = 'Invalid email/password combination' # Not quite right!
      		render 'new'
		end
  	end

  	def destroy
    	sign_out
    	redirect_to root_url	
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, :only => [:edit, :update, :index, :show, :destroy]
  before_filter :correct_user,   :only => [:edit, :update, :show, :destroy]
  before_filter :admin_user,     :only => [:destroy, :index ]
  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        sign_in @user
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, :notice => "Please sign in" 
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callbreak_helper.rb
module CallbreakHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    	cookies.permanent[:remember_token] = user.remember_token
    	self.current_user = user
  	end

	def sign_out
    	self.current_user = nil
    	cookies.delete(:remember_token)
  	end

  	def signed_in?
    	!current_user.nil?
  	end

  	def current_user=(user)
    	@current_user = user
  	end

  	def current_user
    	@current_user ||= User.find_by_remember_token(cookies[:remember_token])
  	end

  	def current_user?(user)
  		user == current_user
  	end


  	 def redirect_back_or(default)
	    redirect_to(session[:return_to] || default)
	    session.delete(:return_to)
	 end

	def store_location
		session[:return_to] = request.url
	end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, :alt => user.name, :class => "gravatar")
  end
end

app/views/callbreak/_playerbottom.html.erb
<h3><%= name %></h3>
<ul class="cards">
	<!-- <li class="first"></li> -->
	<%= i = 0 %>
	<%= margin = 20 %>
  <% player.each do |card| %>
   <%= i = i + 1 %>
   <%= margin = margin + 20 %>
    <li class="card" style="z-index: <%= i %>; margin-left = <%= margin %>px;">
      <%= link_to image_tag("cards/" + card.suit + "-" + card.number + ".png" , :class => 'card'),  :action => 'index', :controller => 'callbreak'%><br>
    </li>
  <% end %>
</ul>

app/views/callbreak/_playerleft.html.erb
<h3><%= name %></h3>
<ul class="cards">
	<!-- <li class="first"></li> -->
	<%= i = 0 %>
	<%= margin = 20 %>
  <% player.each do |card| %>
   <%= i = i + 1 %>
   <%= margin = margin + 20 %>
    <li class="card" style="z-index: <%= i %>; margin-top = <%= margin %>px;">
      <%= link_to image_tag("cards/" + card.suit + "-" + card.number + ".png" , :class => 'card'),  :action => 'index', :controller => 'callbreak'%><br>
    </li>
  <% end %>
</ul>

app/views/callbreak/_playerright.html.erb
<h3><%= name %></h3>
<ul class="cards">
	<!-- <li class="first"></li> -->
	<%= i = 0 %>
	<%= margin = 20 %>
  <% player.each do |card| %>
   <%= i = i + 1 %>
   <%= margin = margin + 20 %>
    <li class="card" style="z-index: <%= i %>; margin-top = <%= margin %>px;">
      <%= link_to image_tag("cards/" + card.suit + "-" + card.number + ".png" , :class => 'card'),  :action => 'index', :controller => 'callbreak'%><br>
    </li>
  <% end %>
</ul>

app/views/callbreak/_playertop.html.erb
<h3><%= name %></h3>
<ul class="cards">
	<!-- <li class="first"></li> -->
	<%= i = 0 %>
	<%= margin = 20 %>
  <% player.each do |card| %>
   <%= i = i + 1 %>
   <%= margin = margin + 20 %>
    <li class="card" style="z-index: <%= i %>; margin-left = <%= margin %>px;">
      <%= link_to image_tag("cards/" + card.suit + "-" + card.number + ".png" , :class => 'card'),  :action => 'index', :controller => 'callbreak'%><br>
    </li>
  <% end %>
</ul>

app/views/callbreak/index.html.erb
<p></p>
<div class="top">
<%= render :partial => 'playertop', :locals => {:player => @player1, :name => "Player 1"} %>
</div>

<div class="middle">
	<div class="left">
	<%= render :partial => 'playerleft', :locals => {:player => @player2, :name => "Player 2"} %>
	</div>

	<div class="right">
	<%= render :partial => 'playerright', :locals => {:player => @player3, :name => "Player 3"} %>
	</div>
</div>

<div class="bottom">
<%= render :partial => 'playerbottom', :locals => {:player => @player4, :name => "Player 4"} %>
</div>

app/views/callbreak/reset.html.erb
<h1>Callbreak#reset</h1>
<p>Find me in app/views/callbreak/reset.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.maharjan.us">Chinny</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Callbreak", '#', :id => "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to current_user.name, current_user %></li>
            <li><%= link_to "Home",    '/' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, :method => 'destroy' %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (yield(:title)) %></title>
    <%= stylesheet_link_tag    'custom' %>
    <%= javascript_include_tag "application" %>

    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<div>
<%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
</div>
<br>
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit "Save changes", :class => "btn btn-large btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <div class="info">
        <%= gravatar_for user %>
        <%= link_to user.name, user %>
      </div>

      <% if current_user.admin? && !current_user?(user) %>
        <div class="action">
          <%= link_to "delete", user, :method => :delete, :class => "delete",
                                        :data => { :confirm => "You sure?" } %>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

<br />
<%= will_paginate %>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <br>
      <%= f.submit "Create my account", :class => "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p>
	<%= gravatar_for @user %>
</p>
<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>